name:                antiope-sqs
version:             4.0.0
github:              "arbor/antiope"
license:             MIT
category:            Services
author:              Arbor Networks
maintainer:          mayhem@arbor.net
copyright:           Arbor Networks

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/arbor/antiope#readme>

default-extensions:
- BangPatterns
- GeneralizedNewtypeDeriving
- OverloadedStrings
- TupleSections

dependencies:
- base >= 4.7 && < 5
- aeson
- amazonka
- amazonka-core
- amazonka-sqs
- amazonka-s3
- antiope-s3
- generic-lens
- lens-aeson
- lens
- network-uri
- monad-loops
- text
- unliftio-core

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -O2
- -msse4.2

library:
  source-dirs: src

tests:
  antiope-sqs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - antiope-sqs
