resolver: lts-13.13

packages:
- antiope-athena
- antiope-core
- antiope-contract
- antiope-dynamodb
- antiope-messages
- antiope-s3
- antiope-sns
- antiope-sqs

extra-deps:
- avro-0.4.3.0
- pure-zlib-0.6.4
- aeson-lens-0.5.0.0
