resolver: lts-11.17

packages:
- antiope-athena
- antiope-core
- antiope-contract
- antiope-dynamodb
- antiope-messages
- antiope-s3
- antiope-sns
- antiope-sqs

- location:
    git: git@github.com:brendanhay/amazonka
    commit: 248f7b2a7248222cc21cef6194cd1872ba99ac5d
    subdirs:
      - amazonka
      - amazonka-athena
      - amazonka-dynamodb
      - amazonka-s3
      - amazonka-sns
      - amazonka-sqs
  extra-dep: true

extra-deps:
- avro-0.3.5.1
- pure-zlib-0.6.4
