resolver: lts-11.15
packages:
- antiope-core
- antiope-s3
- antiope-sqs
- antiope-dynamodb
- antiope-athena

extra-deps:
  - amazonka-1.6.0
  - amazonka-core-1.6.0
  - amazonka-s3-1.6.0
  - amazonka-sqs-1.6.0
  - amazonka-dynamodb-1.6.0
  - amazonka-athena-1.6.0
