version: 2.1

orbs:
  haskell: haskell-works/haskell-build@2.0.3
  hackage: haskell-works/hackage@1.2.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci

      - haskell/build:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci

      # - github/release-cabal:
      #     name: GitHub Release
      #     context: haskell-ci
      #     requires:
      #       - GHC 8.4.4
      #       - GHC 8.6.5
      #     checkout: true
      #     filters:
      #       branches:
      #         only: master

      - hackage/upload:
          context: haskell-ci
          publish: true
          filters:
            branches:
              only: master
          requires:
            - GHC 8.4.4
            - GHC 8.6.5
          #   - GitHub Release


